# Generated by Django 5.1.7 on 2025-04-02 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_shoppinglist_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='item',
            name='unit',
        ),
    ]
