# Generated by Django 5.2 on 2025-05-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0004_remove_item_quantity_remove_item_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(default='g', max_length=30),
            preserve_default=False,
        ),
    ]
